packages:
  - './packages/*'
  - './examples/*'
  - './shared'

allowBuilds:
  lefthook: true
  sharp: false

catalog:
  '@types/node': ^26.1.1
  consola: ^3.4.2
  prettier: ^3.9.6

catalogs:
  react:
    react: ^19.2.8
    react-dom: ^19.2.8
    '@types/react': ^19.2.17
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^6.0.4

  tooling:
    typescript: ^7.0.2
    tsdown: ^0.22.13
    vite: ^8.1.5
